### ISSUE TITLE
entities page

### ISSUE THREAD

**Issue by azahnen** [ldproxy/dashboard#2]
#### Tab Overview

summaries

- cards (from `api/health` and `api/entities`)
  - one card per subtype
  - status as icon (green checkmark, yellow warning sign, etc.)
  - subtypes as badges (e.g. `ogc_api` -> `ogc api`, `features/sql` -> `features` + `sql`)

#### Tab per subtype

one tab for each coarse subtype (the part before the slash), so ogc api, features and tiles

- table or cards or both with switch (from `api/health` and `api/entities`)
  - id
  - subtype
  - status

##### Tab Health

- table (from `api/health` and `api/entities`)

##### Tab Tasks

- table (from `api/tasks`)

##### Tab Configuration

Syntax highlighted YAML from `api/cfg`

#### api/tasks

TBD

#### api/cfg

e.g. `api/cfg/entities/services/bergbau`

```yml
id: vineyards
serviceType: OGC_API
enabled: true
label: Vineyards in Rhineland-Palatinate, Germany
```
